import Head from 'next/head';
import Navbar from '../src/components/Navbar';
export default function Home() {
    return (
        <div>
            <Head>
                <title>Hallothon</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Navbar/>
        </div>
    );
}
