import Head from 'next/head';
import AboutUs from '../src/components/AboutUs';
import Footer from '../src/components/Footer';
import Hero from '../src/components/Hero';
import Navbar from '../src/components/Navbar';
import Sponsor from '../src/components/Sponsor';
export default function Home() {
    return (
        <div>
            <Head>
                <title>Hallothon</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Navbar/>
            <Hero/>
            <Sponsor/>
            <AboutUs/>
            <Footer className='absolute b-0'/>
        </div>
    );
}
